### PR TITLE
Change the way renderer and editor might be passed to HotColumn and HotTable to use render props approach

### PR DESCRIPTION
**Pull request by NOtherDev**
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [x] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by NOtherDev** [comment]
@evanSe I think we haven't discussed Editors deeply enough. 
In HOT, Editors should inherit from `BaseEditor` and override appropriate methods, and I guess this could still be an option in the wrapper and we can apply the same new approach as we did for renderers:


```
<HotTable editor={(props) => <CustomEditorClassComponent {...props} />} />
```

But by the fact that we still need to implement `CustomEditorClassComponent` as a class component, we end up having a not-modern-React-idiomatic class-based code. I think we should provide an alternative that will allow not using own classes - what if we provide a component that gets the possible overrides by props, so that we hide the class stuff from the end-dev?

Sth like:

```
<HotTable editor={(props) => <HotEditor {...props} 
                                        beginEditing={(...params) => customBeginEditing(...params)} />} />
```

WDYT?

**Comment by NOtherDev** [comment]
@evanSe Yet another question - hope you can confirm my thinking or point me to a proper direction.

I'm tracking the usage of `editorCache`, which is typed as `Map<Function, Map<EditorScopeIdentifier, React.Component>>` - two-level map, editor component type as the first level key, `global` or column index as the second level key, editor component instance as the value. The structure suggests as if the editor component type matters here. But while reading the code I don't see how it matters. 

There are just two usages, basically. One that [sets the cache in `emitEditorInstance`](https://github.com/handsontable/handsontable/blob/develop/wrappers/react/src/helpers.tsx#L132) right after the editor was mounted or updated, making sure the cache is always fresh. The second is its read usage when setting up HOT config for either [a table](https://github.com/handsontable/handsontable/blob/develop/wrappers/react/src/hotTableClass.tsx#L270) or [a column](https://github.com/handsontable/handsontable/blob/develop/wrappers/react/src/hotColumn.tsx#L58). In both cases all that matters is actually only the scope (global vs column-specific).

As far as I understand, there can only be up to one editor instance per column + possibly a global one, so all the instances could be cached as well with just `Map<EditorScopeIdentifier, React.Component>`, am I right?

The only possible use case of this multiple-type cache support is if the type of editor switches over time from `A` to `B` and back to `A`, so that `A` instance would already be cached - but looking at the code again, given [a dynamic class is being created](https://github.com/handsontable/handsontable/blob/develop/wrappers/react/src/hotTableClass.tsx#L281) every time the settings change, I don't think this scenario is even supported now (and it would be rather natural that the instance of `A` might not be persisted in such case).

Keeping this complex map type indexed by custom class type will make it impossible to accept editors in a render-props mode like `editor={(props) => <CustomEditor {...props} />}`, because the render prop function is not a class and there will be no way to get `CustomEditor` as a type this way. But, given I think there's no real use case of this deep caching, I think we should simplify the cache and allow this kind of interface.

WDYT?

**Comment by evanSe** [comment]
> @evanSe Yet another question - hope you can confirm my thinking or point me to a proper direction.
> 
> I'm tracking the usage of `editorCache`, which is typed as `Map<Function, Map<EditorScopeIdentifier, React.Component>>` - two-level map, editor component type as the first level key, `global` or column index as the second level key, editor component instance as the value. The structure suggests as if the editor component type matters here. But while reading the code I don't see how it matters.
> 
> There are just two usages, basically. One that [sets the cache in `emitEditorInstance`](https://github.com/handsontable/handsontable/blob/develop/wrappers/react/src/helpers.tsx#L132) right after the editor was mounted or updated, making sure the cache is always fresh. The second is its read usage when setting up HOT config for either [a table](https://github.com/handsontable/handsontable/blob/develop/wrappers/react/src/hotTableClass.tsx#L270) or [a column](https://github.com/handsontable/handsontable/blob/develop/wrappers/react/src/hotColumn.tsx#L58). In both cases all that matters is actually only the scope (global vs column-specific).
> 
> As far as I understand, there can only be up to one editor instance per column + possibly a global one, so all the instances could be cached as well with just `Map<EditorScopeIdentifier, React.Component>`, am I right?
> 
> The only possible use case of this multiple-type cache support is if the type of editor switches over time from `A` to `B` and back to `A`, so that `A` instance would already be cached - but looking at the code again, given [a dynamic class is being created](https://github.com/handsontable/handsontable/blob/develop/wrappers/react/src/hotTableClass.tsx#L281) every time the settings change, I don't think this scenario is even supported now (and it would be rather natural that the instance of `A` might not be persisted in such case).
> 
> Keeping this complex map type indexed by custom class type will make it impossible to accept editors in a render-props mode like `editor={(props) => <CustomEditor {...props} />}`, because the render prop function is not a class and there will be no way to get `CustomEditor` as a type this way. But, given I think there's no real use case of this deep caching, I think we should simplify the cache and allow this kind of interface.
> 
> WDYT?

Went on a investigation on why this piece of code was added in the first place 
- https://github.com/handsontable/handsontable/pull/8901
- https://github.com/handsontable/handsontable/issues/8527

Essentially if there was one custom editor used by two different columns it would use the last defined one even though they had different properties. I tried out `Map<EditorScopeIdentifier, React.Component>` and it works as intended.

I think it was just a mistake in implementation and `Map<EditorScopeIdentifier, React.Component>` should be fine.

I will ask the original author tomorrow (as he is away today) if we are missing anything.

**Comment by evanSe** [comment]
> @evanSe I think we haven't discussed Editors deeply enough. In HOT, Editors should inherit from `BaseEditor` and override appropriate methods, and I guess this could still be an option in the wrapper and we can apply the same new approach as we did for renderers:
> 
> ```
> <HotTable editor={(props) => <CustomEditorClassComponent {...props} />} />
> ```
> 
> But by the fact that we still need to implement `CustomEditorClassComponent` as a class component, we end up having a not-modern-React-idiomatic class-based code. I think we should provide an alternative that will allow not using own classes - what if we provide a component that gets the possible overrides by props, so that we hide the class stuff from the end-dev?
> 
> Sth like:
> 
> ```
> <HotTable editor={(props) => <HotEditor {...props} 
>                                         beginEditing={(...params) => customBeginEditing(...params)} />} />
> ```
> 
> WDYT?

I am currently thinking there could be two approaches

### hooks
```
function EditorComponent({value}: EditorProps) {
  const editor = useEditor();

  const handleValueChange = (event: ChangeEvent<HTMLInputElement>) => {
    const newValue = event.target.value;
    editor.current.setValue(newValue);
  };

  return <input ref={ref} type="text" value={value} onChange={handleValueChange} />;
}
```

### passing props
```
function EditorComponent(props: EditorProps) {
  const { value, setValue } = props;

  const handleValueChange = (event: ChangeEvent<HTMLInputElement>) => {
    const newValue = event.target.value;
    setValue(newValue);
  };

  return <input ref={ref} type="text" value={value} onChange={handleValueChange} />;
}
```

the second approach suggested by you I think would keep things the most simple for now so I would go with that.

**Comment by NOtherDev** [comment]
> I am currently thinking there could be two approaches
> 
> ### hooks
> ```
> function EditorComponent({value}: EditorProps) {
>   const editor = useEditor();
> 
>   const handleValueChange = (event: ChangeEvent<HTMLInputElement>) => {
>     const newValue = event.target.value;
>     editor.current.setValue(newValue);
>   };
> 
>   return <input ref={ref} type="text" value={value} onChange={handleValueChange} />;
> }
> ```
> 
> ### passing props
> ```
> function EditorComponent(props: EditorProps) {
>   const { value, setValue } = props;
> 
>   const handleValueChange = (event: ChangeEvent<HTMLInputElement>) => {
>     const newValue = event.target.value;
>     setValue(newValue);
>   };
> 
>   return <input ref={ref} type="text" value={value} onChange={handleValueChange} />;
> }
> ```
> 
> the second approach suggested by you I think would keep things the most simple for now so I would go with that.

I must admit that I'm not sure I'm following properly. Your code above presents the Editor as if it's a pure React component, decoupled from existing HOT infrastructure, while the current React wrapper impl provides just a layer on top of the native HOT Editor, that is a custom class inheriting from `BaseEditor`. 

I like the code above, but isn't it getting a bit too far from what HOT offers nowadays? Implementing it in the wrapper would require translating an abstract React component into a `BaseEditor`-compatible class, that is translating all the possible React behaviors into pure JS. I guess we can play with `ReactDOM` and `root.render`, but is this what you mean here @evanSe ?

**Comment by evanSe** [comment]
> I must admit that I'm not sure I'm following properly. Your code above presents the Editor as if it's a pure React component, decoupled from existing HOT infrastructure, while the current React wrapper impl provides just a layer on top of the native HOT Editor, that is a custom class inheriting from `BaseEditor`.
> 
> I like the code above, but isn't it getting a bit too far from what HOT offers nowadays? Implementing it in the wrapper would require translating an abstract React component into a `BaseEditor`-compatible class, that is translating all the possible React behaviors into pure JS. I guess we can play with `ReactDOM` and `root.render`, but is this what you mean here @evanSe ?

I think I misunderstood what you initially suggested by
```
<HotTable editor={(props) => <HotEditor {...props} 
                                        beginEditing={(...params) => customBeginEditing(...params)} />} />
```

further looking at it I am a bit confused by `HotTable` having an editor, I would expect it on HotColumn.

I will need some time to properly articulate my suggestion as the EditorClass is a difficult one, It itself is a entire Handsontable (Handsontable in a Handsontable)

**Comment by NOtherDev** [comment]
@evanSe I'm going deeper in analyzing how Editors work and I think I'm missing a piece of knowledge here. I'm not entirely sure what is the reason behind this `editorCache`, regardless what's the key of the map there. I debugged the behaviors there and noticed that:
* Editor components are instantiated once per each `HotTable` render and stay intact for the lifetime of the instance
* once `HotTable` is rerendered - i.e. when its settings change - Editor components are torn down and new ones are instantiated
* the settings intialization has three steps in regards to Editors:
  1. Editor component is being rendered into a Portal in `HotTable`/`HotColumn`
  2. once mounted, `componentDidMount` of `BaseEditorComponent` invokes `emitEditorInstance` which fills the cache
  3. then, parent component (`HotTable`) is mounted/updated, populating HOT settings with dynamic class wrapping the Editor instance read from the cache filled in point 2.

There's no other use of this cache - no change within the table itself trigger the rerender so the cache isn't needed; OTOH, every change in the table settings cause full replacement of Editors so the cache isn't needed either. Thus, given we are planning to change the structure, I don't see any need to keep that cache at all. Unless I'm totally missing something. Hope you can clear my doubts @evanSe  🙂

**Comment by evanSe** [comment]
> There's no other use of this cache - no change within the table itself trigger the rerender so the cache isn't needed; OTOH, every change in the table settings cause full replacement of Editors so the cache isn't needed either. Thus, given we are planning to change the structure, I don't see any need to keep that cache at all. Unless I'm totally missing something. Hope you can clear my doubts @evanSe 🙂

I looked deeply into this and have come to the same conclusion of removing the editor cache.

could you explain your idea around `<HotTable editor={(props) => <HotEditor {...props} beginEditing={(...params) => customBeginEditing(...params)} />} />` a little more? as the only approach I see at the moment would be HotColumn creating an editor class and exposing the editor via context

so if you create an editor you will have available 

```
// inside of a editor component
const {setValue} = useEditor({
// bad examples
prepare: () => {}
})
```

**Comment by NOtherDev** [comment]
I spent some time investigating how Editors actually work and I withdraw my `HotEditor` proposal mentioned above - it wouldn't work nicely anyway.

Editors are basically classes that consume events emitted by HOT core, and HOT expects the editor to implement a number of handlers for these events. I think the proper React idiom for this is [`useImperativeHandle`](https://react.dev/reference/react/useImperativeHandle) hook. It allows to [expose imperative functions](https://react.dev/reference/react/useImperativeHandle#exposing-your-own-imperative-methods) (event handlers - base editor method overrides) to the higher component by ref, so that the higher component (HOT core) can invoke them on the instance.

```
const CustomEditor = forwardRef((props, ref) => {
    useImperativeHandle(ref, () => ({
        finishEditing: () => // custom impl
        focus: () => // custom impl
        // etc.
    })

   // rest omitted
   return <p/>
})
```

We can wrap it into custom hook called `useHotEditorHooks` for example for clear naming and strong typing. The user will be able to provide all the needed hooks this way and leave the others undefined, falling back to `BaseEditor` versions. The code that instantiates the Editor will just need to grab the `ref` and forward the calls appropriately. WDYT?

--
BTW why in your example `setValue` Editor's hook is treated differently?

**Comment by evanSe** [comment]
> I spent some time investigating how Editors actually work and I withdraw my `HotEditor` proposal mentioned above - it wouldn't work nicely anyway.
> 
> Editors are basically classes that consume events emitted by HOT core, and HOT expects the editor to implement a number of handlers for these events. I think the proper React idiom for this is [`useImperativeHandle`](https://react.dev/reference/react/useImperativeHandle) hook. It allows to [expose imperative functions](https://react.dev/reference/react/useImperativeHandle#exposing-your-own-imperative-methods) (event handlers - base editor method overrides) to the higher component by ref, so that the higher component (HOT core) can invoke them on the instance.
> 
> ```
> const CustomEditor = forwardRef((props, ref) => {
>     useImperativeHandle(ref, () => ({
>         finishEditing: () => // custom impl
>         focus: () => // custom impl
>         // etc.
>     })
> 
>    // rest omitted
>    return <p/>
> })
> ```
> 
> We can wrap it into custom hook called `useHotEditorHooks` for example for clear naming and strong typing. The user will be able to provide all the needed hooks this way and leave the others undefined, falling back to `BaseEditor` versions. The code that instantiates the Editor will just need to grab the `ref` and forward the calls appropriately. WDYT?
> 

Love this idea, lets go with it!

> -- BTW why in your example `setValue` Editor's hook is treated differently?

I would ignore my example

**Comment by NOtherDev** [comment]
Superseded with #4 and #5.

**Pull request closed without merging**
